# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04 #ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          .github/workflows/retry.sh sudo apt-get update
          .github/workflows/retry.sh sudo apt-get install --quiet -y build-essential libcurl4 libcurl4-openssl-dev
      - name: Download V
        run: |
          tag="latest"
          .github/workflows/retry.sh wget https://github.com/vlang/v/releases/$tag/download/v_linux.zip
          unzip v_linux.zip
          cd v
          ./v -version
      - name: Compile
        run: |
          cd v
          ./v ../src -o ../cht

      - name: Test cht
        run: ./cht --version
      
